services:
  base:
    image: ros2_base
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: jazzy
        USER_NAME: $USER_NAME
        USER_ID: $USER_ID
        GROUP_NAME: $GROUP_NAME
        GROUP_ID: $GROUP_ID
      target: ros2_base
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
