services:
  dev:
    image: ros2_dev
    extends:
      file: docker-compose.base.yml
      service: base
    # debugging
    cap_add:
      - SYS_PTRACE
    privileged: true
    # Interactive shell
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw # gui
      - /home/$USER_NAME/.ssh:/home/$USER_NAME/.ssh:ro # git credentials
      - /home/$USER_NAME/data:/home/$USER_NAME/data:rw
      - /dev/bus/usb:/dev/bus/usb # for usb access, depends where its located
      - ../workspaces:/home/$USER_NAME/workspaces
