services:
  base:
    image: ros2_base
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: jazzy
      target: ros2_base
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
